# Load packages
library(shiny)
library(shinyjs)
library(shinyjqui)
library(shinyFiles)
library(shinyWidgets)
library(bslib)
library(bsicons)
library(rgbif)
library(DT)
library(sf)
library(dplyr)
library(tidyr)
library(purrr)
library(stringr)
library(lubridate)
library(forcats)
library(igraph)
library(camtraptor)
library(camtrapDensity)
library(activity)
library(overlap)
library(highcharter)
library(mapview)
library(leaflet)
library(leaflet.extras)
library(leaflet.minicharts)
library(leafsync)
library(INBOtheme)
library(ggplot2)
library(promises)
library(future)

# Resolve namespace conflicts
conflicted::conflicts_prefer(dplyr::select)
conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(dplyr::lag)
conflicted::conflicts_prefer(DT::dataTableOutput)
conflicted::conflicts_prefer(DT::renderDataTable)
conflicted::conflicts_prefer(camtraptor::pred_in)

# Source helper files
source("R/functions.R")
source("R/n_observations.R")